### ISSUE TITLE
No instruction for use with Huggingface models

### ISSUE THREAD

**Issue by bahadirery** [Renumics/rag-demo#10]
Why there are no instructions to use with open source embedding models? The notebook does not work because you can not create docs/data and fill it unless you are paying for OpenAI api.

**Comment by markus-stoll** [comment]
Thanks for your post - we are working on an example based on open source models from hugging face. 

I will publish an article [at medium](https://medium.com/@markus.stoll), if its done.  You can subscribe there to get an email when its publish, if you want to.

**Comment by bahadirery** [comment]
Thank you for your answer. I appreciate your hard work and will be waiting for the article.

**Comment by markus-stoll** [comment]
Here is a another article with code by [Kennedy Selvadurai](https://medium.com/@heelara?source=user_profile-------------------------------------) of using spotlight visualization with TinyLlama 1.1B: [Visualizing FAISS Vector Space to Understand its Influence on RAG Performance](https://medium.com/ai-advances/visualizing-faiss-vector-space-to-understand-its-influence-on-rag-performance-14d71c6a4f47)

**Comment by druzsan** [comment]
Hi @bahadirery, there is also docstring on top of the [assistant module](https://github.com/Renumics/rag-demo/blob/main/assistant/__init__.py) which briefly explains how to use different models (Hugging Face, OpenAI, Azure OpenAI). You can use them interchangeably (even combine OpenAI embeddings with HF LLMs or vice versa).

In case you don't want to add our repository to dependencies, just unravel the code from the module:
```python
import torch
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.llms.huggingface_pipeline import HuggingFacePipeline
from transformers import pipeline

# Use desired models here
embeddings_model_name = "thenlper/gte-base"
llm_name = "google/flan-t5-base"

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
embeddings_model = HuggingFaceEmbeddings(
    model_name=embeddings_model_name,
    encode_kwargs={"normalize_embeddings": True},
    model_kwargs={"device": device},
)
llm = HuggingFacePipeline(
    pipeline=pipeline(model=llm_name, device=device, max_length=2048)
)
```

For usage example, refer to the @markus-stoll's [article](https://itnext.io/visualize-your-rag-data-eda-for-retrieval-augmented-generation-0701ee98768f) or module docstring mentioned above.
