### ISSUE TITLE
LangChain Issue

### ISSUE THREAD

**Issue by greydoubt** [Renumics/rag-demo#5]
Do one without LangChain, the dependencies for it make it not usable

**Comment by druzsan** [comment]
Hi @greydoubt, could you provide more explanation? Would you prefer to use LlamaIndex or pure OpenAI/Hugging Face with Vectorstores instead?

IMHO, LangChain is quite lightweight itself and it doesn't lock different unnecessary dependencies and you can choose your own subset of them instead depending on models your working with.
